# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9d000835e0072d02f659bfa26a407fbbd4d15e1ed95f394c667de9557097e21d87b88b703a2b93d618764b5202b961687c8b11359644bf776c5c3853695e47b

test:
  secret_key_base: 7d47313480ff5c5085d65fcc635a1de928e657664f0343bb78d5fa7af76b21bbffb1f6eccad28b8df949955d23a97c8608a66daba254b5ed2d7f696767a933d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
